// Generated by CoffeeScript 1.4.0
(function() {
  var change, decorators, dgram, helpers, send;

  dgram = require('dgram');

  helpers = require('helpers');

  decorators = require('decorators');

  exports.send = send = function(msg) {
    var client, message;
    message = new Buffer(JSON.stringify(msg));
    client = dgram.createSocket("udp4");
    return client.send(message, 0, message.length, 41234, "localhost", function(err, bytes) {
      return client.close();
    });
  };

  exports.watch = function(graph, source, frequency, f) {
    var watcher;
    watcher = function() {
      return send({
        graph: graph,
        source: source,
        push: f()
      });
    };
    return setInterval(watcher, frequency);
  };

  exports.change = change = function(graph, source, change) {
    return send({
      graph: graph,
      source: source,
      change: change
    });
  };

}).call(this);
